### ISSUE TITLE
missing table is not created?

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#8]
I ran the import process against baglung and it failed with over 1900 messages which said "Error encountered!".

I guessed that might correspond to one error per object and added the table into the database by hand. The second run finished without error.

The unit test code calls the table creation when needed. I'll need to look more closely at the integration code to see if it is tested there.

**Comment by btbonval** [comment]
This issue has just been confirmed on Travis.
```
Running "mochaTest:integration" (mochaTest) task

  Integration

Error encountered!
  1) "before all" hook
Error encountered!

  0 passing (2s)
  1 failing

  1) Integration "before all" hook:
     Error: relation "couchdata" does not exist
      at Error (native)
      at wrapError (common.js:7:11)
      at common.js:19:19
      at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:489:16)
      at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:501:17)
      at lib$rsvp$$internal$$publish (node_modules/rsvp/dist/rsvp.js:472:11)
      at lib$rsvp$$internal$$publishRejection (node_modules/rsvp/dist/rsvp.js:415:7)
      at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1290:9)
```

**Comment by btbonval** [comment]
On my local machine, I can delete the given database and the integration test still succeeds (it creates the relation and populates it). The checkout commit is the same for travis and my local system. Time to play a rousing game of "what's different?"

I'm wondering if the postgres setup is not being performed as expected on Travis or if somehow I'm missing a step there.

**Comment by btbonval** [comment]
On my local env, I ran the following two commands as postgres user (which appear to work fine on Travis based on output):
```
psql -c "CREATE ROLE medictest WITH LOGIN PASSWORD 'password';" -U postgres
psql -c "CREATE DATABASE medicdata WITH OWNER medictest;" -U postgres
```

Then I created a file with env vars to `source` based on `.travis.yml` settings:
```
#travis
export POSTGRESQL_URL="postgres://medictest:password@localhost:5432/medicdata"
export POSTGRESQL_TABLE="couchdata"
export POSTGRESQL_COLUMN="json"
#export COUCHDB_URL="http://localhost:5984/medic/_all_docs?include_docs=true"

#from local VM
export COUCHDB_URL='http://bryan:password@192.168.56.101/medic/_all_docs?include_docs=true'
```

I ran `grunt ci`. Interestingly, I get no errors, but the integration test fails. I went to check the database to see what was in it and quickly found the error on my local system:
```
$ psql -U medictest medicdata
psql: FATAL:  Peer authentication failed for user "medictest"
```

Of course on my local postgres, I've disabled password auth and only trust unix domain auth. This makes me wonder if the Travis postgres settings preclude certain forms of access. I still can't replicate the error I see on Travis.

**Comment by btbonval** [comment]
Local system now works totally fine with `.travis.env` settings except for local postgres user issue. Still, Travis claims that the relation `couchdata` is not found as though the table is not made.

I'm not sure what else to do here besides use the `postgres` user outright, since I know for sure that works without error to create databases and roles and it is the only thing documented for accessing postgres in Travis docs.

**Comment by btbonval** [comment]
NOPE.

I got nothing. You win Travis. Your mysteries are too mysterious for me.

**Comment by btbonval** [comment]
Travis does not create the table because JSONB is not a valid type! Is this actually running 9.4 as requested?

Some debug which explains a _lot_:
```
$ psql -d ${POSTGRESQL_URL} -c "CREATE TABLE couchdata (jsondata JSONB);"

ERROR:  type "jsonb" does not exist

LINE 1: CREATE TABLE couchdata (jsondata JSONB);
```

**Comment by btbonval** [comment]
Travis cannot build a table with a jsonb column because it is running 9.1:
```
0.06s$ psql --version

psql (PostgreSQL) 9.4.0

$ psql -d ${POSTGRESQL_URL} -c "SELECT version();"

                                                   version                                                   

-------------------------------------------------------------------------------------------------------------

 PostgreSQL 9.1.14 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3, 64-bit

(1 row)
```


I think this issue comment addresses the problem. Apparently many people make the mistake in YAML of adding a hyphen where there should be none.
https://github.com/travis-ci/travis-ci/issues/2983#issuecomment-75420000

Sure enough I have a hyphen, and sure enough the travis CI docs exclude a hyphen. Apparently this is the difference between an object and an array in YAML:
``` yaml
addons:
  postgresql: "9.3"
```

``` yaml
addons:
  - postgresql: "9.3"
```

**Comment by btbonval** [comment]
Still getting red on Travis, but the integration failure clearly indicates the table was created.

Both local and Travis can create table. This ticket is now lies.
